const AttendanceTableMockData = () => {
  const mockData = [
    {
      id: 1,
      name: "John Doe",
      clockIn: "08:00 AM",
      clockOut: "05:00 PM",
      department: "Software",
      attendanceStatus: "Present",
      email: "john.doe@example.com",

      types: ["attendance", "earlyClockIn", "extraBreakTaken"],
    },
    {
      id: 2,
      name: "Biraj Doe",
      clockIn: "09:30 AM",
      clockOut: "06:30 PM",
      department: "Management",
      attendanceStatus: "Present",
      email: "biraj.doe@example.com",
      types: ["attendance", "extraBreakTaken"],
    },
    {
      id: 3,
      name: "Bob Smith",
      clockIn: "10:15 AM",
      clockOut: "07:45 PM",
      department: "Software",
      attendanceStatus: "Absent",
      email: "bob.smith@example.com",
      types: ["absent"],
    },
    {
      id: 4,
      name: "Alice Johnson",
      clockIn: "08:45 AM",
      clockOut: "05:15 PM",
      department: "Management",
      attendanceStatus: "Present",
      email: "alice.johnson@example.com",
      types: ["late", "attendance"],
    },
    {
      id: 5,
      name: "David Brown",
      clockIn: "09:00 AM",
      clockOut: "06:00 PM",
      department: "Manager",
      attendanceStatus: "Present",
      email: "david.brown@example.com",
      types: ["late"],
    },
    {
      id: 6,
      name: "Laura White",
      clockIn: "10:30 AM",
      clockOut: "07:30 PM",
      department: "Software",
      attendanceStatus: "Present",
      email: "laura.white@example.com",
      types: ["attendance", "extraBreakTaken"],
    },
    {
      id: 7,
      name: "Michael Miller",
      clockIn: "08:15 AM",
      clockOut: "05:45 PM",
      department: "Management",
      attendanceStatus: "Present",
      email: "michael.miller@example.com",
      types: ["attendance", "extraBreakTaken"],
    },
    {
      id: 8,
      name: "Eva Lee",
      clockIn: "09:45 AM",
      clockOut: "07:00 PM",
      department: "Software",
      attendanceStatus: "Absent",
      email: "eva.lee@example.com",
      types: ["leaveTaken", "LateClockin"],
    },
    {
      id: 9,
      name: "Mark Wilson",
      clockIn: "08:30 AM",
      clockOut: "05:30 PM",
      department: "Management",
      attendanceStatus: "Present",
      email: "mark.wilson@example.com",
      types: ["absent"],
    },
    {
      id: 10,
      name: "Sophia Taylor",
      clockIn: "09:15 AM",
      clockOut: "06:45 PM",
      department: "Manager",
      attendanceStatus: "Absent",
      email: "sophia.taylor@example.com",
      types: ["earlyClockIn", "attendance"],
    },

    {
      id: 11,
      name: "Chris Anderson",
      clockIn: "08:00 AM",
      clockOut: "05:00 PM",
      department: "Software",
      attendanceStatus: "Present",
      email: "chris.anderson@example.com",
      types: ["attendance", "earlyClockIn"],
    },
    {
      id: 12,
      name: "Emma Davis",
      clockIn: "09:30 AM",
      clockOut: "06:30 PM",
      department: "Management",
      attendanceStatus: "Absent",
      email: "emma.davis@example.com",
      types: ["extraBreakTaken", "LateClockin"],
    },
    {
      id: 13,
      name: "Aaron White",
      clockIn: "10:15 AM",
      clockOut: "07:45 PM",
      department: "Software",
      attendanceStatus: "Present",
      email: "aaron.white@example.com",
      types: ["attendance"],
    },
    {
      id: 14,
      name: "Olivia Brown",
      clockIn: "08:45 AM",
      clockOut: "05:15 PM",
      department: "Management",
      attendanceStatus: "Present",
      email: "olivia.brown@example.com",
      types: ["attendance"],
    },
    {
      id: 15,
      name: "Daniel Smith",
      clockIn: "09:00 AM",
      clockOut: "06:00 PM",
      department: "Manager",
      attendanceStatus: "Absent",
      email: "daniel.smith@example.com",
      types: ["leaveTaken", "LateClockin"],
    },
  ];

  return mockData;
};

export default AttendanceTableMockData;
